/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ex02;

import java.text.NumberFormat;
import java.text.ParseException;
import java.util.Locale;
import javax.swing.ButtonGroup;


/**
 *
 * @author J&L
 */
public class jFrTela extends javax.swing.JFrame {

    private final ButtonGroup entradaGroup;
    private final ButtonGroup saidaGroup;
    /**
     * Creates new form jFrTela
     */
    public jFrTela() {
        initComponents();
        entradaGroup = new ButtonGroup();
        entradaGroup.add(radBRealEntrada);
        entradaGroup.add(radBDolarEntrada);
        entradaGroup.add(radBEuroEntrada);
        
        saidaGroup = new ButtonGroup();
        saidaGroup.add(radBRealSaida);
        saidaGroup.add(radBDolarSaida);
        saidaGroup.add(radBEuroSaida);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textf_Entrada = new javax.swing.JTextField();
        textf_Saida = new javax.swing.JTextField();
        btLimpar = new javax.swing.JButton();
        radBRealEntrada = new javax.swing.JRadioButton();
        radBDolarEntrada = new javax.swing.JRadioButton();
        radBEuroEntrada = new javax.swing.JRadioButton();
        radBRealSaida = new javax.swing.JRadioButton();
        radBDolarSaida = new javax.swing.JRadioButton();
        radBEuroSaida = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Concersor de Moeda");

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Moeda que será convertida");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Moeda da conversão");

        textf_Entrada.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        textf_Entrada.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textf_Entrada.setText("0,00");
        textf_Entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textf_EntradaActionPerformed(evt);
            }
        });

        textf_Saida.setEditable(false);
        textf_Saida.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        textf_Saida.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textf_Saida.setText("0,00");
        textf_Saida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textf_SaidaActionPerformed(evt);
            }
        });

        btLimpar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        radBRealEntrada.setText("Real R$");
        radBRealEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBRealEntradaActionPerformed(evt);
            }
        });

        radBDolarEntrada.setText("Dolar US$");
        radBDolarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBDolarEntradaActionPerformed(evt);
            }
        });

        radBEuroEntrada.setText("Euro €");
        radBEuroEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBEuroEntradaActionPerformed(evt);
            }
        });

        radBRealSaida.setText("Real R$");
        radBRealSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBRealSaidaActionPerformed(evt);
            }
        });

        radBDolarSaida.setText("Dolar US$");
        radBDolarSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBDolarSaidaActionPerformed(evt);
            }
        });

        radBEuroSaida.setText("Euro €");
        radBEuroSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBEuroSaidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textf_Entrada, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textf_Saida)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radBRealEntrada)
                                .addGap(108, 108, 108)
                                .addComponent(radBDolarEntrada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                                .addComponent(radBEuroEntrada))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radBRealSaida)
                                .addGap(108, 108, 108)
                                .addComponent(radBDolarSaida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(radBEuroSaida))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btLimpar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radBRealEntrada)
                    .addComponent(radBEuroEntrada)
                    .addComponent(radBDolarEntrada))
                .addGap(39, 39, 39)
                .addComponent(textf_Entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radBRealSaida)
                    .addComponent(radBDolarSaida)
                    .addComponent(radBEuroSaida))
                .addGap(24, 24, 24)
                .addComponent(textf_Saida, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btLimpar)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void radBEuroSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBEuroSaidaActionPerformed
        radBRealSaida.setSelected(false);
        radBDolarSaida.setSelected(false);
    }//GEN-LAST:event_radBEuroSaidaActionPerformed

    private void radBRealEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBRealEntradaActionPerformed
        radBDolarEntrada.setSelected(false);
        radBEuroEntrada.setSelected(false);
    }//GEN-LAST:event_radBRealEntradaActionPerformed

    private void radBDolarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBDolarEntradaActionPerformed
        radBRealEntrada.setSelected(false);
        radBEuroEntrada.setSelected(false);
    }//GEN-LAST:event_radBDolarEntradaActionPerformed

    private void radBEuroEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBEuroEntradaActionPerformed
        radBRealEntrada.setSelected(false);
        radBDolarEntrada.setSelected(false);
    }//GEN-LAST:event_radBEuroEntradaActionPerformed

    private void radBRealSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBRealSaidaActionPerformed
        radBEuroSaida.setSelected(false);
        radBDolarSaida.setSelected(false);
    }//GEN-LAST:event_radBRealSaidaActionPerformed

    private void radBDolarSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBDolarSaidaActionPerformed
        radBRealSaida.setSelected(false);
        radBEuroSaida.setSelected(false);
    }//GEN-LAST:event_radBDolarSaidaActionPerformed

    private void textf_EntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textf_EntradaActionPerformed
              // Obtém o texto do campo textf_Entrada
        String entradaText = textf_Entrada.getText();

        // Cria um objeto NumberFormat para o formato padrão do Brasil
        NumberFormat format = NumberFormat.getNumberInstance(new Locale("pt", "BR"));

        try {
            // Faz o parsing do texto para um número
            Number entradaNumber = format.parse(entradaText);

            // Converte o número para um inteiro
            int entradaInt = entradaNumber.intValue();

            // Exibe o número inteiro (apenas para fins de depuração)
            System.out.println("Entrada Inteira: " + entradaInt);
            textf_Saida.setText(String.valueOf(entradaInt));
        } catch (ParseException ex) {
            // Se ocorrer um erro de parsing, imprime o erro
            System.err.println("Erro ao fazer o parsing do texto de entrada: " + ex.getMessage());
        }
    }//GEN-LAST:event_textf_EntradaActionPerformed

    private void textf_SaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textf_SaidaActionPerformed

    }//GEN-LAST:event_textf_SaidaActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
    entradaGroup.clearSelection();
    saidaGroup.clearSelection();
    textf_Entrada.setText("0,00");
    textf_Saida.setText("0,00");
    }//GEN-LAST:event_btLimparActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton radBDolarEntrada;
    private javax.swing.JRadioButton radBDolarSaida;
    private javax.swing.JRadioButton radBEuroEntrada;
    private javax.swing.JRadioButton radBEuroSaida;
    private javax.swing.JRadioButton radBRealEntrada;
    private javax.swing.JRadioButton radBRealSaida;
    private javax.swing.JTextField textf_Entrada;
    private javax.swing.JTextField textf_Saida;
    // End of variables declaration//GEN-END:variables
}
